PART2_PROCESS_TREE:
  children:
  - children:
    - level: 2
      name: level2.1
      print: true
      token: ''
    level: 1
    name: level1.1
    print: true
    token: c56d1d
  - children:
    - level: 2
      name: level2.2
      print: false
      token: ''
    level: 1
    name: level1.2
    print: true
    token: '296270'
  - children:
    - level: 2
      name: level2.3
      print: true
      token: ''
    - level: 2
      name: level2.4
      print: false
      token: ''
    level: 1
    name: level1.3
    print: false
    token: 74919d
  - children:
    - level: 2
      name: level2.5
      print: true
      token: ''
    level: 1
    name: level1.4
    print: false
    token: 958e1c
  level: 0
  name: level0
  print: true
  token: c56d1d29627074919d958e1c
